# Generated by Django 4.0.6 on 2022-07-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescope_alter_article_options_scope_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='articlescope',
            old_name='scope',
            new_name='tag',
        ),
    ]
